# Nginx needs an events block even if empty
events {}

http {
    server {
        listen 80;  # Expose port 80 to the host

        # Forward all traffic to the backend Flask API
        location / {
            proxy_pass http://backend:5000;
        }
    }
}